[package]
name = "xraydb-data"
version = "0.1.0"
edition = "2024"
authors = ["Ameyanagi <contact@ameyanagi.com>"]
license = "MIT OR Apache-2.0"

[dependencies]
serde = { version = "1", default-features = false, features = ["derive", "alloc"] }
